### ISSUE TITLE
styling request: display function name multiple-arities vertically instead horizontally

### ISSUE THREAD

**Issue by uvtc** [zk/clojuredocs#101]
For example, the top of http://clojuredocs.org/clojure.core/subseq would be more readable, IMO, if it were displayed vertically as:

~~~
(subseq sc test key)
(subseq sc start-test start-key end-test end-key)
~~~

instead of (as it currently displays):

~~~
(subseq sc test key)  (subseq sc start-test start-key end-test end-key)
~~~

**Comment by zk** [comment]
The problem is that functions with 5 or 6 arities cause a bunch of open space to the right, and push the juicy stuff down past the fold. I'd be open to more granular handling of these cases though, feel free to open a PR.
