### ISSUE TITLE
The recommeneded style for examples is often not followed

### ISSUE THREAD

**Issue by phreed** [zk/clojuredocs#103]
The bulk of the examples do not conform to the http://clojuredocs.org/examples-styleguide.
The examples provided include a 'prompt' indicating the current namespace
and show the result without comment characters. e.g.
user> (+ 2 3)
5

My understanding is that if the namespace is anything other than user
it should be preceded by a "use" to make it clear what the current namespace is.
This could be clearer in the styleguide.

Should these be updated as they are encountered? 
or is this alternate form acceptable?
My guess is that the bulk of these examples are coming in from prior work.
Should there be a script for updating these examples as they are imported?

**Comment by zk** [comment]
Hey @phreed,

Yes, please update as encountered. You're correct on your guess, there's a lot of legacy formatting in the examples.

Small side note, I'm going to change the style guide to prefer `require` over `use`, as `:require [... :refer ...]` has become the idiomatic way to pull in non fully qualified vars into the current namespace. Thanks for the heads up.

**Comment by zk** [comment]
Ah, to answer your last question. A script to update all the examples would be nice, but it seems like it would be a huge PITA to build. There might be an easy 80% thing though, so feel free to give it a shot.

**Comment by zk** [comment]
Update to the docs is shipped.
