### ISSUE TITLE
try, catch and finally -- confusingly share same description

### ISSUE THREAD

**Issue by cwreynolds** [zk/clojuredocs#104]
The doc for these three special forms is written to describe how they interact. This is the context in what I assume is the original source of the text at http://clojure.org/special_forms (to which the reader is directed for more information, although none is actually available there). However in http://clojuredocs.org/ the same text is repeated in three separate entries for the three forms. This is particularly confusing if the reader starts at the entry for `catch` or `finally`.

My impression is that either the three entries should be combined into one (like at http://clojure.org/special_forms), or that the text for `catch` and `finally` should be modified to be specific to those forms. I would be happy to propose alternate text, but wanted to know if I was on the right track here.

**Comment by zk** [comment]
Hey @cwreynolds,

Unfortunately there's no "slot" for community-sourced doc strings right now, but it's something I'd be really interested in seeing.

Down the line it would be great to have a way to submit this directly through the site, but a nice first cut would be to have a section just under the official doc which renders a markdown file from source, like on the namespace pages:

http://clojuredocs.org/clojure.core.async
https://github.com/zk/clojuredocs/blob/master/src/md/namespaces/clojure.core.async.md

Feel free to propose alternate text, and I can take a look at getting it onto the site. If you're feeling especially adventurous you can submit a PR.
