### ISSUE TITLE
User examples gone?

### ISSUE THREAD

**Issue by raj-kesavan** [zk/clojuredocs#108]
Example: http://clojuredocs.org/clojure.core/case

Before there used to be user comments and examples; now they're gone. Any chance of getting them back?

**Comment by zk** [comment]
Hey @raj-kesavan, I'm seeing the examples / comments. Do you have JS turned off in your browser? If not are you getting any errors?


![](filesystem:chrome-extension://fdpohaocaechififmbbbbbknoalclacl/temporary/screencapture-clojuredocs-org-clojure-core-case.png)

**Comment by raj-kesavan** [comment]
I'm on Firefox Developer with JS turned on.

    (Warning) The character encoding of a framed document was not declared.
The document may appear different if viewed without the document framing
it. github-btn.html
    (Error) uncaught exception: Invalid match arg: /^[.#]/ <unknown>




---
Balachandar 'Raj' Kesavan

**Comment by zk** [comment]
Thanks for the update, fixed in 50ccdd9607477a9adb1d5d7bc374bd1cc98098b3, shipping now.

**Comment by raj-kesavan** [comment]
Awesome! Thanks.

**Comment by zk** [comment]
@raj-kesavan can you double-check on your end?

**Comment by raj-kesavan** [comment]
Yeah, it's working.


---
Balachandar 'Raj' Kesavan
