### ISSUE TITLE
Characters are not escaped in docstrings properly

### ISSUE THREAD

**Issue by mishok13** [zk/clojuredocs#109]
As can be seen in [core.async/alts!](https://clojuredocs.org/clojure.core.async/alts!) characters like `<` and `>` are not escaped, leaving a piece of docstring hidden. To be more exact, the following text:
```Takes will be made as if by !```
should have been rendered as
```"Takes will be made as if by <!, and puts will be made as if by >!."```
but this doesn't happen. If you don't have time for this currently I can take a look at possible fix later this week, however I have absolutely zero experience with clojuredocs internals. :)

**Comment by zk** [comment]
Thanks @mishok13
