### ISSUE TITLE
Add new vars for Clojure 1.7.0

### ISSUE THREAD

**Issue by jafingerhut** [zk/clojuredocs#110]
I know as I create this issue that Clojure 1.7.0-RC1 has just been released, not the final 1.7.0 release, but I have done some updates to a local copy of the Clojure cheat sheet to include new vars from 1.7.0 into it, including a new section on transducers.  I will probably hold off from publishing it until 1.7.0 is officially released, and you may be waiting for that same event for updating ClojureDocs.org.

**Comment by zk** [comment]
Thanks Andy. I'll follow suit and get a PR ready to merge and deploy once
the release is live.

**Comment by jafingerhut** [comment]
Just a heads up that at least one doc string will probably be added after Clojure 1.7.0-RC1, so you may want to postpone the generation of ClojureDocs.org content until the final 1.7.0 release, unless you do not mind doing it a couple of times to get the latest version.

**Comment by zk** [comment]
@jafingerhut no worries, docstrings are actually pulled from the runtime at startup, so all it takes is a version bump: https://github.com/zk/clojuredocs/pull/111

**Comment by cloojure** [comment]
Hi - I have noticed that clojure.core/update is missing from ClojureDocs:  http://clojuredocs.org/search?q=update

What is the best way of fixing this?
Alan

**Comment by zk** [comment]
Hey @cloojure, looks like that's in now: http://clojuredocs.org/clojure.core/update
