### ISSUE TITLE
wrong return values in examples for `boolean`? Sort of?

### ISSUE THREAD

**Issue by AlexKnauth** [zk/clojuredocs#114]
Here:
https://clojuredocs.org/clojure.core/boolean
In this:
```clojure
;; Everything except `false' and `nil' is true in boolean context.
user=> (into {} (map #(vector % (boolean %)) [true false nil [] {} '() #{} ""]))
{true true, false false, nil false, [] true, {} true, #{} true, "" true}
```
What happened to the entry for `'()`?

Except that clojure does seem to do that, so is that a bug in clojure, or is there some weird intentional reason that it forgets about the `'()` entry?

And, is there a better way of writing that example that avoids that confusion?

**Comment by blx** [comment]
Yeah that is rather unintuitive.

The problem is that
```clojure
=> (= '() [])
true
```
so the example boils down to
```clojure
=> (into {} [[[] true]
             [() true]])
{[] true}
```
It first adds the entry `{[] true}` to the map and then updates that entry with `{() true}`. The value is still `true`, so that doesn't change, and the keys are equal, so they don't change:

```clojure
=> (def z :a)
#'user/z
=> (into {} [[:a true] [:b false] [z false]])
{:a false, :b false}
```

---
**Solution:**
We could skip the `into` and just print the map?
```clojure
user=> (map #(vector % (boolean %)) [true false nil [] {} '() #{} ""])
([true true] [false false] [nil false] [[] true] [{} true] [() true] [#{} true] ["" true])

user=> (clojure.pprint/pp)
([true true]
 [false false]
 [nil false]
 [[] true]
 [{} true]
 [() true]
 [#{} true]
 ["" true])
nil
```

**Comment by blx** [comment]
Or even
```clojure
(map (juxt identity boolean) [true false nil ...])
```

**Comment by AlexKnauth** [comment]
Yes, one of those would make more sense. I hadn't come across `juxt` yet though.

**Comment by zk** [comment]
Hey guys, I've updated the comment with the explanation. Feel free to update it (and remove the comment I added) if you can clarify further.

Thanks!

**Comment by AlexKnauth** [comment]
Thanks you!
