### ISSUE TITLE
No entries for new, monitor-enter, monitor-exit

### ISSUE THREAD

**Issue by jafingerhut** [zk/clojuredocs#118]
At least not that I could find via search box, or on the clojure.core symbol page

**Comment by zk** [comment]
Fixed by 40e323dd35b3116fca9ab48d0ec9427f44864906, up on prod now.

![](http://cl.ly/image/3e0I1T0Z1j0I/Screen%20Shot%202015-07-15%20at%2012.03.29%20PM.png)

**Comment by jafingerhut** [comment]
Still nothing for 'new'

**Comment by zk** [comment]
Ah, I read that as "No entries for new monitor-enter, monitor-exit".

**Comment by zk** [comment]
Fixed by 32620d2, up on prod.

![](http://cl.ly/image/1p1L2g1w3G3J/Screen%20Shot%202015-07-15%20at%2012.46.25%20PM.png)
