### ISSUE TITLE
How to delete an invalid example?

### ISSUE THREAD

**Issue by kajism** [zk/clojuredocs#120]
I'm wondering what to do with this example on keep fn published on clojuredocs:

http://clojuredocs.org/clojure.core/keep#example-5521c980e4b0b96203a0d59d

I think it should be deleted, because:

1) the first part
```clojure
;;it is equivalent to:
;;user=> (filter identity (map f coll))
```
is NOT true:
```clojure
(filter identity (map identity [false nil]))
;;=> ()
(keep identity [false nil])
;;=> (false)
```
2) the second part
```clojure
;;also useful with maps
(keep {:a 1, :b 2, :c 3} [:a :b :d])
;;=> (1 2)
```

I'm wondering if this can be ever usefull, because we don't know what keys where missing, so the result is who knows what... Or am I missing something?

**Comment by zk** [comment]
Hey @kajism,

In general:

1. Factually incorrect information should definitely be removed.
2. Factually correct but questionably useful information should be preserved. I'm thinking 'questionable usefulness' is highly subjective, so let's leave it up to the reader to determine what's useful (or not). This could lead to the case where great content could buried under a mound of mediocre content, but let's cross that bridge when we get there.

How's that sound?

**Comment by kajism** [comment]
Hello @zk,

sounds good, but what to do with the above case?
I'm new to Clojure, so I would prefer correct info on clojuredocs. Some experienced moderator would be great.

**Comment by zk** [comment]
@kajism I think you should change it (remove the incorrect part). You're the one that found the incorrect info, so I would say you're sufficiently experienced :smile:.

Here's the [examples styleguide](http://clojuredocs.org/examples-styleguide), which can provide you with some context for what we're looking for in examples. Let me know if you have any questions.

**Comment by zk** [comment]
I just realized that this may not be obvious: log in, and you can edit any example. You'll see a little 'edit' link pop up:

![](http://cl.ly/image/3T1C123K0p1O/Screen%20Shot%202015-10-26%20at%201.49.16%20PM.png)

**Comment by kajism** [comment]
Yes, I know. And I almost done it like this:
```clojure
;;it is NOT equivalent to:
;;user=> (filter identity (map f coll))
(filter identity (map identity [false nil]))
;;=> ()
(keep identity [false nil])
;;=> (false)

;;also can be used with maps
(keep {:a 1, :b 2, :c 3} [:a :b :d])
;;=> (1 2)
```

But I just really don't want to be connected with some from-my-point-of-view-stupid examples. Why should people waste their time reading it? IMHO, I suggest to delete it :)

**Comment by zk** [comment]
@kajism Yes, I agree. How about this:

![](http://cl.ly/image/262x2K2z1O1g/Screen%20Shot%202015-10-26%20at%202.36.06%20PM.png)

**Comment by kajism** [comment]
Thanks for understanding @zk :)
Unfortunately I have personally also problem with the meaning of "useful with maps" in this context. I'm very sorry :(

**Comment by Ishanshah301190** [comment]
I am getting this error when I am trying to start the server with the (go) command.
Can someone help me with this
BindException Address already in use: bind  sun.nio.ch.Net.bind0 (Net.java:-2)
