### ISSUE TITLE
Server Error

### ISSUE THREAD

**Issue by Ishanshah301190** [zk/clojuredocs#121]
I am getting this error when I am trying to start the server with the (go) command.
Can someone help me with this
BindException Address already in use: bind  sun.nio.ch.Net.bind0 (Net.java:-2)

**Comment by zk** [comment]
@Ishanshah301190 I'm not familiar with the `(go)` command, can you provide more context?

**Comment by Ishanshah301190** [comment]
(go) is a command which we can use in the cmd to start the server for leiningen

**Comment by zk** [comment]
@Ishanshah301190 I'm not sure where that command comes from, perhaps a lein plugin? In any case, ClojureDocs is run from the commandline via the `bin/dev` script: https://github.com/zk/clojuredocs#dev
