### ISSUE TITLE
Typo defonce description.

### ISSUE THREAD

**Issue by tarunama** [zk/clojuredocs#125]
I may think typo in this page description.
http://clojuredocs.org/clojure.core/defonce

defs name to have the root value of the expr iff the named var has no root value,
else expr is unevaluated
↓
defs name to have the root value of the expr if the named var has no root value,
else expr is unevaluated

**Comment by zk** [comment]
Hey @tarunama, good catch. I believe in this case 'iff' is correct, in that it refers to the shortened version of 'If and only if'. https://en.wikipedia.org/wiki/If_and_only_if
