### ISSUE TITLE
Quickref is missing symbols such as `and`, `or`, `not`, and `let`

### ISSUE THREAD

**Issue by IshmaelYavitz** [zk/clojuredocs#126]
I noticed that they don't appear on https://clojuredocs.org/quickref .

**Comment by IshmaelYavitz** [comment]
There are others but I'm not keeping a list.  Would be easier just to diff against a list of symbols in core.

**Comment by zk** [comment]
Thanks @IshmaelYavitz

**Comment by IshmaelYavitz** [comment]
My pleasure.

But do note that there are more symbols in core that are missing from the quickref.  I just stopped listing them manually since I thought it would result in a more comprehensive list if you were to diff the symbols listed in the quickref against those in core.

**Comment by zk** [comment]
Cool, thanks for the heads up. I think that's ok, as the quickref is more for getting an overview of the available vars, rather than a comprehensive list of everything that's in core.

**Comment by IshmaelYavitz** [comment]
Ah, okay.  Thanks for this fix.
