### ISSUE TITLE
Documentation for throw is the documentation for recur

### ISSUE THREAD

**Issue by AGBrown** [zk/clojuredocs#130]
The documentations for clojure.core/throw is not the documentation for `throw`, but the documentation for `recur`

See: http://clojuredocs.org/clojure.core/throw
And see: http://clojuredocs.org/clojure.core/recur

This is what it should be: 

 - [Clojure.org > Special Forms > throw](http://clojure.org/special_forms#Special Forms--(throw expr))
 - http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/throw

**Comment by zk** [comment]
Good catch, thanks @AGBrown
