### ISSUE TITLE
Page titles looking weird because of non-monospace font

### ISSUE THREAD

**Issue by Dominionized** [zk/clojuredocs#131]
Some pages that contain special symbols like dashes look a bit weird without a monospace font. For example, on my machine the "->" page looks like this. The dash could even be mistaken for an underscore.
![image](https://cloud.githubusercontent.com/assets/5436916/12533433/9e55bcda-c1fd-11e5-87fd-257c821ae4b6.png)

**Comment by zk** [comment]
Hrm, that's odd, here's what it looks like for me:

![](http://cl.ly/2W2s213L2l3P/Screen%20Shot%202016-01-23%20at%203.51.09%20PM.png)

Which browser / os are you on? Perhaps the fonts aren't loading correctly.

**Comment by Dominionized** [comment]
I'm on Windows 10 with Chrome 48. The rendered font is Arial, although when I change it manually to Helvetica, it looks more like your screenshot :
![image](https://cloud.githubusercontent.com/assets/5436916/12534502/b052b2d6-c229-11e5-93a6-e44400077753.png)

It's a bit better but they're still not aligned exactly. I guess the font wasn't designed to display symbols like that. Maybe using a monospace font on the page titles would be a good idea ? (Since they're code)
I tried it manually and imho it looks pretty nice plus it looks more consistent with the snippets below :
![image](https://cloud.githubusercontent.com/assets/5436916/12534516/7ee10422-c22a-11e5-9719-3ca8f4c3796e.png)

Anyways, thanks for the quick reply

**Comment by zk** [comment]
@Dominionized took another look at this today, I like the way the non-monospace font looks for var page titles. Thanks!
