### ISSUE TITLE
The documentation for reify could be better

### ISSUE THREAD

**Issue by bpicolo** [zk/clojuredocs#133]
Link here:
https://clojuredocs.org/clojure.core/reify

First and foremost, it doesn't actually tell you what reify does at all, which is by far the most unfortunate bit. In addition, though, this really just muddles an already-pretty-confusing piece of functionality

**Comment by zk** [comment]
Hi @bpicolo, these docstrings are pulled directly from Clojure source, so you'll have to put in a patch there: http://dev.clojure.org/display/community/Developing+Patches
