### ISSUE TITLE
'map-entry?' function is missing

### ISSUE THREAD

**Issue by ertugrulcetin** [zk/clojuredocs#134]
There is no info about '**map-entry?**' function in http://clojuredocs.org

Here is the usage:
Doc: "Return true if x is a map entry"

user=> (map-entry? (first (seq {:foo 1 :bar 2})))
;;=> true

user=> (map-entry? (seq {:foo 1 :bar 2}))
;;=> false

**Comment by zk** [comment]
@ertugrulcetin see #132
