### ISSUE TITLE
Include the core.logic sub-libraries

### ISSUE THREAD

**Issue by freckletonj** [zk/clojuredocs#135]
At: https://github.com/clojure/core.logic/tree/master/src/main/clojure/clojure/core/logic

There's a scarcity of resources for learning `core.logic`, and a lot of the coolness of `core.logic` is in things like `core.logic.fd`.

Especially, I'd love to see on ClojureDocs:
Finite Domains: https://github.com/clojure/core.logic/blob/master/src/main/clojure/clojure/core/logic/fd.clj
Pldb: https://github.com/clojure/core.logic/blob/master/src/main/clojure/clojure/core/logic/pldb.clj

**Comment by zk** [comment]
Added, thanks @freckletonj

**Comment by freckletonj** [comment]
@zk that is so freakin awesome! Thanks so much for clojuredocs, it's seriously my most useful tool besides clojurians on slack. ClojureDocs Rocks. So. Hard. Thanks!
