### ISSUE TITLE
core.async refers to "port" instead of "channel"

### ISSUE THREAD

**Issue by cloojure** [zk/clojuredocs#137]
Hi,

It looks like most of the core.async docs refer to a "port" instead of a "channel", esp. in the header areas.  I'd like to fix this, but the header areas (basic function description) don't seem to be editable. 

How should I approach this?

Thanks,
Alan

**Comment by zk** [comment]
Hey Alan! It's great that you'd like to help out, unfortunately it's not something you can fix on ClojureDocs -- that text comes directly from Clojure. For example: 

https://github.com/clojure/core.async/blob/master/src/main/clojure/clojure/core/async.clj#L101

I believe you'd have to submit a patch to  to fix that: http://dev.clojure.org/display/community/Developing+Patches

Thanks anyway.

**Comment by zk** [comment]
2nd thought: are you sure that ports and channels are synonymous? A quick glance through the source seems to indicate a deliberate distinction, but I didn't see what that might be.

**Comment by cloojure** [comment]
Hi - I have never heard the term "port" before seeing it on ClojureDocs
today.  I think it is just an early working term.  We'll see what Alex has
to say.
Alan

**Comment by cloojure** [comment]
From Alex
---------------------------------------

Hi Alan, this project does not accept PRs - we manage patches via JIRA at
http://dev.clojure.org/jira/browse/ASYNC.

However, the use of port in these docstrings is intentional - a port can be
seen as a "channel end" and is an abstraction that is not really used at
the moment but may be in the future (as a narrower abstraction than
"channel").
