### ISSUE TITLE
defmethod invalid syntax

### ISSUE THREAD

**Issue by laforge49** [zk/clojuredocs#142]
from: http://clojuredocs.org/clojure.core/defmethod

(defmulti service-charge (fn [acct] [(account-level acct) (:tag acct)]))
(defmethod service-charge [::acc/Basic ::acc/Checking]   [_] 25)
(defmethod service-charge [::acc/Basic ::acc/Savings]    [_] 10)
(defmethod service-charge [::acc/Premium ::acc/Account] [_] 0)

If I put ::acc/Basic in my repl, it reports:

RuntimeException Invalid token: ::acc/Basic  clojure.lang.Util.runtimeException (Util.java:221)

**Comment by zk** [comment]
@laforge49 would you mind updating the example on site? You just need to log in to edit examples.
