### ISSUE TITLE
Wrong function called in tree-seq example

### ISSUE THREAD

**Issue by bbakersmith** [zk/clojuredocs#143]
The example here... 

https://clojuredocs.org/clojure.core/tree-seq#example-542692d5c026201cdc3270ad

...shows two identical forms returning different results. In the second example, seen below, the call to seq? should be a call to sequential? instead.

```
;; notice the difference between seq? and sequential?
(tree-seq seq? seq [[1 2 [3]] [4]])
;;=> ([[1 2 [3]] [4]] [1 2 [3]] 1 2 [3] 3 [4] 4)
```

**Comment by zk** [comment]
@bbakersmith thanks for the heads up, you're able to edit that yourself directly on the `tree-seq` page, all you need to do is log in.
