### ISSUE TITLE
Source links still point to Clojure 1.7.0 tag

### ISSUE THREAD

**Issue by samestep** [zk/clojuredocs#144]
c7cc652b5c68892b9165edcbc1b99062cb1a906a updates ClojureDocs to Clojure 1.8.0; however, the source links still point to the [clojure-1.7.0] tag instead of the [clojure-1.8.0] tag, as demonstrated by this [Boot] script:

```clojure
#!/usr/bin/env boot

(set-env! :dependencies '[[hickory "0.6.0"]])

(require '[hickory.core :refer :all]
         '[hickory.select :as s])

(->> "https://clojuredocs.org/clojure.core/+"
     slurp
     parse
     as-hickory
     (s/select (s/child (s/class :source-link) (s/tag :a)))
     (run! (comp println :href :attrs)))
```

## Expected output

```
https://github.com/clojure/clojure/blob/clojure-1.8.0/src/clj/clojure/core.clj#L965
```

## Actual output

```
https://github.com/clojure/clojure/blob/clojure-1.7.0/src/clj/clojure/core.clj#L965
```

[boot]: http://boot-clj.com/
[clojure-1.7.0]: https://github.com/clojure/clojure/tree/clojure-1.7.0
[clojure-1.8.0]: https://github.com/clojure/clojure/tree/clojure-1.8.0

**Comment by zk** [comment]
Whoops, thanks @samestep

**Comment by zk** [comment]
Fixed by 460c5d3

**Comment by zk** [comment]
Excellent ticket @samestep, super helpful with the repro instructions 🙏

**Comment by samestep** [comment]
Thanks for fixing this so quickly! :+1:
