### ISSUE TITLE
Can anyone edit or add in an example? (sounds dangerous)

### ISSUE THREAD

**Issue by functor-soup** [zk/clojuredocs#145]
I was looking at an example related to `reduced` and came across this example of this one guy implementing `some` using `reduced` and his code was as follows:

[https://clojuredocs.org/clojure.core/reduced](https://clojuredocs.org/clojure.core/reduced)
```
(defn resome [pred koll]
  (reduce (fn [_ c] (when (pred c) (do (pred c) (reduced (pred c)))))
          koll))
```
And I'm like wait a minute doesn't `when` already have an implicit `do` and proceeded to take it out and accidentally omitted the `(pred c)` after it, but seems like it perfectly works fine (the following is what I ended up with)

```
(defn resome [pred koll]
  (reduce (fn [_ c] (when (pred c) (reduced (pred c))))
          koll)) 
```
So then I tried to correct it thinking that someone will probably have to review the code I put in, but it got published as soon as I clicked `save`.

So I was wondering em shouldn't there be someone reviewing these examples if this is a learning resource?  The error is a result of version changes and the guy's example was probably perfectly correct in ref to some older version of clojure or I probably violated some `best practices rules` Or maybe I am the jackass who is missing something here? Again my question is shouldn't there someone who is reviewing the examples?

**Comment by zk** [comment]
Yes anybody can edit any review. In theory, yeah somebody could go through and really abuse the system, but in practice people seem to be pretty chill.

FWIW all changes are saved in the DB so it's possible to roll back changes. There's just no UI for it at the moment.

**Comment by zk** [comment]
Oh, and thanks for updating the example!
