### ISSUE TITLE
ClojureScript compatibility

### ISSUE THREAD

**Issue by ghost** [zk/clojuredocs#146]
it would be nice if there is some room/fields to explicitly define/describe compatibility with ClojureScript.
e.g. if something is not implemented in ClojureScript, or when a function has a slightly different behaviour in ClojureScript

In the UI, notes on ClojureScript could then be visualised in a different color, or with a 'ClojureScript' label

**Comment by zk** [comment]
Hey @sj4. Great idea, and I think this is rolled up with a set "ClojureScript support on ClojureDocs" features like differentiation in search, source linking, and probably a few more I haven't thought about.

The tough part is that ClojureDocs uses the Clojure runtime as a database -- existence of vars is queried at start-up and made browsable and searchable -- so cljs vars aren't queryable using this method. Seems like the steps to get CLJS vars into the current system would be:

* Find or write a cljs metadata parser
* Export data structures to the codebase where they can be tracked in version control
* Read and import those at app startup

These also could be stored in the DB, but I'd rather keep them in VC where changes can be tracked.

I like your idea of keeping clj & cljs vars on the same page when their namespaces and names match up, and calling out different behavior inline on the page somewhere (vs separate pages for clj & cljs vars with the same ns & name).

Just getting my thoughts out here, I'm working through some maintenance and code cleanup right now so I'll look at tackling something like this after I'm done with that.

**Comment by ProbonoBonobo** [comment]
@zk Big thanks for maintaining my favorite Clojurescript cheatsheet. I think I might have some bandwidth in the very near future to help out. A few quick questions about this guy:

>     Export data structures to the codebase where they can be tracked in version control

Could you describe the structure you had in mind – and maybe which specific attributes of the docpage you'd like to track in version control? 

Should the responsibility for generating any associated metadata (e.g., hashes/checksums) fall on the put method, or on the version control system? (I reckon it's probably a good idea to make sure the hashes are different before appending anything, and merge the computed hash into any entries that go in.)

Should entries be tokenized before they go into the database? (If so, a spec defining the properties of a DBEntry object would be helpful.)

**Comment by zk** [comment]
Hey @ProbonoBonobo!

I was thinking it would just be a single edn file in the codebase somewhere that's read at startup to seed the lucene index we use to support things like search and loading up data for var pages.

At startup the clojuredocs app gathers all available vars using Clojure's namespace introspection functions (`find-ns`, `ns-publics`, etc). The nice thing is that this makes it easy to add new vars when a new version of Clojure is released (just bump the Clojure version number in `project.clj`). The downside is that this won't work for ClojureScript or (eventually) third party libs.

You can see the gathering process here: https://github.com/zk/clojuredocs/blob/master/src/clj/clojuredocs/search.clj#L102

Some vars that can't be found through this process, like special forms, are added manually.

Anyways, to answer your questions:

> Could you describe the structure you had in mind

Off the top of my head: it would be a monolithic map in an edn file, something like:

```
{:library-url "https://github.com/clojure/clojure"
 :version "1.8.0"
 :source-base-url "https://github.com/clojure/clojure/1.8.0/blob" ; to provide source linking
 :namespaces [NAMESPACE...]}

NAMESPACE
{:name "clojure.core"
 :doc "...."
 :vars [VAR...]}

VAR
{:ns "clojure.core"
 :name "map"
 :file "..."
 :line 1234
 :added "1.0"
 :arglists [(map f) (map f coll) (map f c1 c2) ...]
 :doc "Returns a lazy sequence consisting of..."
 :deprecated false}
```

> Should the responsibility for generating any associated metadata

I'm not sure hashes are necessary? There's no concept of different versions of vars in the codebase right now, if it's in the current version then you can find it on ClojureDocs, if not, you get a 404.


> Should entries be tokenized before they go into the database?

There's a post processing step that adds the ClojureDocs url and applies the 'type' of the var (function, macro, etc), and maybe some other stuff, but the structure is pretty similar to what you get from var metadata.

**Comment by zk** [comment]
One more thing to note, any user-submitted info like examples, notes, and see-alsos are stored in Mongo and keyed via a var's namespace, name, and library-url (to prevent collisions across libs).
