### ISSUE TITLE
clj->js and js->clj links return 404 Error [Clojurescript Cheatsheet]

### ISSUE THREAD

**Issue by ProbonoBonobo** [zk/clojuredocs#147]
The greater than symbol appears to break the URL.

[Linking page](http://cljs.info/cheatsheet/)
[Broken clj->js link](http://clojuredocs.org/clojure.core/clj->js)
[Broken js->clj link](http://clojuredocs.org/clojure.core/js->clj)

**Comment by zk** [comment]
@ProbonoBonobo clojuredocs only hosts Clojure vars ATM. At some point I'll get ClojureScript vars in there as well, but for now this is correct.

http://clojuredocs.org/clojure.core/->
