### ISSUE TITLE
`clojure.spec` support

### ISSUE THREAD

**Issue by freckletonj** [zk/clojuredocs#151]
I've just gotta say, clojuredocs is an inestimable help when it comes to learning new clojure libs, and `spec` is an obvious next candidate, I think.

Thanks for all you do!

**Comment by zk** [comment]
I was waiting until 1.9 came out, but I suppose there's no harm in getting it in now. 

My only hesitation would be if 1.9 removes any vars  available in 1.8, as these would be removed from the site as well. Do you know if that's the case?

**Comment by freckletonj** [comment]
I have no clue, sorry

**Comment by jafingerhut** [comment]
@zk I can confirm that 1.9 does not remove any vars that were present in 1.8.  It adds some, and removes none.  Confirmed using some code that I have for helping to generate the Clojure cheatsheet.  Also, in Rich Hickey's Clojure/Conj 2016 talk Spec-ulation (worth watching -- https://www.youtube.com/watch?v=oyLBGkS5ICk&list=PLZdCLR02grLofiMKo0bCeLHZC0_2rpqsz ), he explains why it would be very unlikely he would ever remove any vars from Clojure, and explains why it is a bad idea to do so in other code.

**Comment by zk** [comment]
@jafingerhut oh great, thanks for checking. Really enjoyed the talk.

Fixed by 87b517a8b294649e1cf7e9df3d1324945ea13d7c

**Comment by zk** [comment]
And 95b5d8bd4a9e5adba1508393d72b5006a2c35827

**Comment by zk** [comment]
Deployed now
