### ISSUE TITLE
Scrolling trouble

### ISSUE THREAD

**Issue by broose** [zk/clojuredocs#154]
Scrolling at "Namespaces" side panel at https://clojuredocs.org/clojure.zip unavailable.

Screenshot:
https://www.dropbox.com/s/n8uwcoq9zhna5vt/Screenshot%20from%202016-12-24%2020-48-09.png?dl=0

Good day for ya :slightly_smiling_face:

**Comment by zk** [comment]
@broose can you verify?

**Comment by broose** [comment]
@zk works
Not from the very top though: [link](https://www.dropbox.com/s/jgn20pgfphlh54k/Screenshot%20from%202017-01-03%2011-08-31.png?dl=0)
It appears if scroll down a little main section of the page: [link](https://www.dropbox.com/s/mudw4uqqtoo4seq/Screenshot%20from%202017-01-03%2011-08-15.png?dl=0)

**Comment by zk** [comment]
@broose great, I'm ok with that. Thanks for checking.
