### ISSUE TITLE
Should redirect to secure version of site

### ISSUE THREAD

**Issue by timmc** [zk/clojuredocs#155]
Now that Clojuredocs has a jobs board, it's especially important that redirect HTTP -> HTTPS to protect people's privacy.

(Later: HSTS?)

**Comment by zk** [comment]
Yeah sounds great. FWIW we don't collect any info from users past their GH handles for posting content, and none for the jobs section.

I'm thinking letsencrypt is the right call for this. Do they support HSTS? I'm not familiar with it, but I'm hoping it's supported by the major desktop and mobile browsers?

**Comment by timmc** [comment]
I was thinking more along the lines of a use-case like "my employer should not be able to tell the difference between me looking up docs vs. looking up jobs". :-)

Letsencrypt is great, but... it looks like you already *have* TLS support! e.g. https://clojuredocs.org/clojure.core/juxt

**Comment by zk** [comment]
> I was thinking more along the lines of a use-case like "my employer should not be able to tell the difference between me looking up docs vs. looking up jobs". :-)

Hah, excellent point!

Ok, looks like TLS is provided by Cloudflare (see 'Flexible SSL'): https://support.cloudflare.com/hc/en-us/articles/200170416-What-do-the-SSL-options-mean-

According to their docs this should only be used as a stopgap, so I'll look into the Let's Encrypt process and start prepping for the switch over.

**Comment by zk** [comment]
Fixed by b2e8fb974cbc31880100663b7b900102432f2d1b. Thanks @timmc

**Comment by timmc** [comment]
Fantastic, thank you!
