### ISSUE TITLE
Protocols

### ISSUE THREAD

**Issue by ghost** [zk/clojuredocs#156]
would be nice to have an overview of all standard protocols in Clojure as a reference. Currently the only docs I could find are in the source of Clojure itself.

use case: I want to implement ISwap on a custom type, but I forgot about all different variations to be implemented. I head to ClojureDocs to  quickly find the documentation, and perhaps some additional examples

**Comment by zk** [comment]
Yeah, seems like this would be really helpful. Do you know if there's an easy way to get this info other than parsing the source files?
