### ISSUE TITLE
Link to page in search results not working

### ISSUE THREAD

**Issue by DjebbZ** [zk/clojuredocs#170]
Steps to reproduce :

- go to https://clojuredocs.org/
- type "Destructuring" in search bar
- click on "Destructuring" in suggestions

Expected results : navigate to https://clojuredocs.org/concepts/destructuring

Actual results : nothing happens :(

May be the bug is on results of type "Page", links work on other types of results (at least "Var", "Function", "Macro").

**Comment by ptmartin** [comment]
looks like this issue and issue #175 are related.

**Comment by zk** [comment]
Fixed by 6398ca805b7ab293f3a09c31be40b5d9fa6d571a
