### ISSUE TITLE
special forms don't have a source location but still have a source link

### ISSUE THREAD

**Issue by dpsutton** [zk/clojuredocs#178]
special forms have a source link in the top right corner but the link is malformed. An example is `set!` [link](https://clojuredocs.org/clojure.core/set!) Which has the malformed source link [https://github.com/clojure/clojure/blob/clojure-1.9.0-alpha14/src/clj/#L](https://github.com/clojure/clojure/blob/clojure-1.9.0-alpha14/src/clj/#L). `def` also has this same defect. Probably true of all of the special forms.

**Comment by Deraen** [comment]
If I understand clojuredocs code correctly after few minutes, the special-forms data is declared here: https://github.com/zk/clojuredocs/blob/master/src/clj/clojuredocs/data/import.clj#L231

`:file` and `:line` data could be added here to point to `clojure.lang.Compiler` where these are implemented, e.g. `set!`: https://github.com/clojure/clojure/blob/clojure-1.9.0-alpha14/src/jvm/clojure/lang/Compiler.java#L596
Though, I'm not sure how helpful the Java code would be for most of users. And manually set line number would break if file is updated. So maybe it is easiest to just hide source links for these forms.

**Comment by zk** [comment]
Good solution @Deraen, thanks.
