### ISSUE TITLE
Certificate issues reported in Chrome devtools

### ISSUE THREAD

**Issue by hipitihop** [zk/clojuredocs#184]
On Chrome Version 63.0.3239.132 (Official Build) (64-bit) in devtools

`"The SSL certificate used to load resources from https://d1lpkba4w1baqt.cloudfront.net will be distrusted in M70. Once distrusted, users will be prevented from loading these resources. See https://g.co/chrome/symantecpkicerts for more information."`

`The SSL certificate used to load resources from https://bam.nr-data.net will be distrusted in M70. Once distrusted, users will be prevented from loading these resources. See https://g.co/chrome/symantecpkicerts for more information`

**Comment by zk** [comment]
Thanks for the heads up
