### ISSUE TITLE
Update the MongoDB dumps

### ISSUE THREAD

**Issue by ckoparkar** [zk/clojuredocs#185]
The data from ClojureDocs is currently used to support the `see-also` documentation feature in CIDER. The `cider-nrepl` has an edn file generated from this database, which is queried to show `see-also` links for `clojure.core`. We'd like to add support Clojure 1.9 functions as well. Could you please upload the latest MongoDB database dumps here ?

/cc @bbatsov

**Comment by zk** [comment]
Here you go https://cl.ly/0R1M0Z0n1F3Y/clojuredocs-clean-db-backup-20180120.tar.gz

@bbatsov I can provide an endpoint where you can get this as a JSON dump if you let me know the structure cider expects.

**Comment by ckoparkar** [comment]
Thanks a lot @zk!

A sample of the edn file used in the nrepl, which is a quite different from the structure stored in the database.

```
{"clojure.core/conj!" ["clojure.core/transient" "clojure.core/assoc!" "clojure.core/dissoc!" "clojure.core/conj"],
 "clojure.core/the-ns" ["clojure.core/ns-name"]}
```

For the API, exposing the db structure, modulo a few changes would work just as well. Will wait to hear @bbatsov's thoughts.

**Comment by zk** [comment]
Great do you have a link to the edn file so I can see it in context?

**Comment by ckoparkar** [comment]
Ah, sorry. Here's the link: https://github.com/clojure-emacs/cider-nrepl/blob/master/resources/see-also.edn

**Comment by bbatsov** [comment]
@zk Out of curiosity - how do you generate these relations in the first place?

**Comment by zk** [comment]
@ckoparkar @bbatsov this work? https://clojuredocs.org/api/exports/see-alsos-relations

**Comment by ckoparkar** [comment]
This is perfect. It's exactly the same format. Thanks a lot for all the help @zk!

**Comment by zk** [comment]
No prob, happy to help.

**Comment by MicahElliott** [comment]
@zk How often is that `see-alsos-relations` file generated?  I'm not seeing updates from a few days ago reflected in it.  The see-alsos are a really useful graph for various things.  It'd be nice if cider could keep pretty closely up-to-date with it.  It's also great for generating graphs (like graphviz) of the interconnectedness of all the clojure functions, and possibly other things.
