### ISSUE TITLE
Quickref Usability

### ISSUE THREAD

**Issue by jared-ross** [zk/clojuredocs#189]
Hi zk,

I really like the Quickref feature, it allows me to browse clojure by functionality rather than alphabetically which isn't very useful.

What I don't like about it is that as soon as I click on something it leaves Quickref.

I would like to update Quickref such that clicking on an item changes the content but keeping the Quickref outline on the side.

Would it be ok if I worked on this?

Thanks,

Jared

**Comment by zk** [comment]
Hi Jared,

Appreciate the offer but I'd like to keep it as is. Sometimes I'll command-click (which opens a new tab) to preserve my place on the quickref.
