### ISSUE TITLE
Can I has an API?

### ISSUE THREAD

**Issue by PEZ** [zk/clojuredocs#192]
It seems the API is down since a while? What would it take to bring it up again? Can we help in some way to make it happen?

I am right now only in need of a way to read out entries, if that can scope it down any.

**Comment by dpsutton** [comment]
In a related note, there's https://clojuredocs.org/clojuredocs-export.json which seems to be a recent-ish dump. Can this be distributed and changed in format for tooling like CIDER?

**Comment by zk** [comment]
Thanks @dpsutton!

**Comment by Bost** [comment]
Hi, could you create a new dump please (with some creation timestamp) or even better make the http://api.clojuredocs.org/ working? Thank you.
