### ISSUE TITLE
Add new vars from Clojure 1.10

### ISSUE THREAD

**Issue by jafingerhut** [zk/clojuredocs#198]
If they are already there and I've missed them, glad to be shown where to find them.

Clojure 1.10 contains at least one new namespace clojure.datafy that was not in Clojure 1.9.

This is probably a complete list of namespaces in Clojure 1.10: https://github.com/jafingerhut/clojure-cheatsheets/blob/master/src/clj-jvm/src/generator/core.clj#L1367-L1404

If the line numbers get off with future commits, just search for the symbol name `all-clojure-built-in-namespaces`

**Comment by zk** [comment]
Oh great, thanks Andy. I will take a look when I have some time.

**Comment by ilyabe** [comment]
@jafingerhut I have a little [pull request](https://github.com/zk/clojuredocs/pull/202) for this. Thanks for helping me get the project running locally in the Clojure Slack :-)

**Comment by zk** [comment]
Merged ad7aa9d19b0e5e20b2991a5be82672e532789fa9

**Comment by zk** [comment]
Deployed

**Comment by jafingerhut** [comment]
Excellent!

If you don't mind having a message in #announcements channel on Clojurians Slack, I think it is worth a mention of this update.  I can make one, if you would prefer not to.

**Comment by zk** [comment]
Yeah great idea. I don’t have my laptop with me so if you don’t mind
posting one please do.

**Comment by jafingerhut** [comment]
Done.
