### ISSUE TITLE
Searching on page finds hidden text

### ISSUE THREAD

**Issue by nate** [zk/clojuredocs#199]
There is text hidden by `text-overflow` on function list pages and like the one for [clojure.core](https://clojuredocs.org/clojure.core) (search for `map` and the 4th match is hidden) and using the browser's find-in-page still matches them, which makes searching confusing. Could we make a way to optionally show all the text, or truncate it so it's not found by the browser's find function?

**Comment by nate** [comment]
It actually [looks pretty good](https://user-images.githubusercontent.com/130/60624087-0aa38300-9daa-11e9-9690-79f54cceccf4.png) if you disable `whitespace: nowrap` and `overflow: hidden` and `text-overflow: ellipsis`.

**Comment by zk** [comment]
@nate I'd like to keep them to a single line, truncating on the server side would be tough to support responsively. Might be an issue to raise with your browser.
