### ISSUE TITLE
Do you have a plan to export data as EDN format?

### ISSUE THREAD

**Issue by liquidz** [zk/clojuredocs#200]
I knew clojuredocs is exporting data as JSON format at here.
https://clojuredocs.org/clojuredocs-export.json

If there is a EDN format exported data, it is easy to use in other clojure projects including CIDER.
https://github.com/clojure-emacs/cider/issues/2663#issuecomment-508985865

Do you have a plan to export data as EDN format?

**Comment by zk** [comment]
Hi Masashi, I don’t have any plans for an EDN export at the moment.

**Comment by liquidz** [comment]
OK! Thanks!
