### ISSUE TITLE
[feature request] add "edit this page" button on each page

### ISSUE THREAD

**Issue by dheerajbhaskar** [zk/clojuredocs#204]
## Context
I wanted to update the copy in [reduce](https://clojuredocs.org/clojure.core/reduce). I couldn't find the page to edit for the life of me

## Request
Add an edit this page button like a wiki has. I understand this is not a wiki, but I think will be useful.

## Willing to give a PR
If you point me to where the copy is stored, I can perhaps figure out a way to implement this. I spend like 30 min going through the repo without finding where the copy for reduce is stored. I'm sure people would've encountered this scenario earlier

**Comment by dheerajbhaskar** [comment]
I realized it's here: https://github.com/clojure/clojure/blob/clojure-1.9.0/src/clj/clojure/core.clj#L6730

Would you suggest providing a pull request to the Clojure repo or is there any possibility of changing it in this repo?

Changes I was going to do:
- Stylistic changes to separate out that there are two scenarios: 1. When val is supplied 2. When val is not supplied

**Comment by zk** [comment]
@dheerajbhaskar The copy comes directly from Clojure docstrings, so there's no possibility of changing them from this repo.
