### ISSUE TITLE
How often is clojuredocs-export.json updated?

### ISSUE THREAD

**Issue by jafingerhut** [zk/clojuredocs#206]
I read this article recently: https://metaredux.com/posts/2019/12/14/exporting-clojuredocs-as-edn.html and was glad to learn of the existence of the file https://clojuredocs.org/clojuredocs-export.json

It appears that the number that is the value of the top level "created-at" key in that JSON file represents a time on the day 2018-Nov-20.  Does that mean this file is updated manually on some irregular schedule?  Or automatically, but only very infrequently like once per year?  If it could be updated regularly, e.g. once per week or so, that would help consumers of this data (e.g. Cider documentation, the Clojure cheat sheet) to stay more up to date.

**Comment by zk** [comment]
IIRC it’s a daily task, the process may have quit though. I’ll check later
today and update this ticket.

**Comment by zk** [comment]
Daily exports back up now. Thanks for the heads up.

**Comment by jafingerhut** [comment]
And thanks for the fix!
