### ISSUE TITLE
Link up the reference for Binding Forms

### ISSUE THREAD

**Issue by alper** [zk/clojuredocs#207]
I had a hard time finding the documentation for how the bindings are documented.

Say on this page:
https://clojuredocs.org/clojure.core/loop

It would be nice if the string "binding-forms" in the main documentation was linked up to:
https://clojure.org/reference/special_forms#binding-forms

It probably makes sense to repeat that on other relevant pages as well (`let` etc.).

**Comment by zk** [comment]
Great idea, something for future development.
