### ISSUE TITLE
Mailgun API key

### ISSUE THREAD

**Issue by sdushantha** [zk/clojuredocs#212]
Hey,

I just wanted to let you know that I found your `MAILGUN_API_KEY` in "[clojuredocs/bin/.devenv](clojuredocs/bin/.devenv)" and Im not sure if you want that to be public because Mailgun is paid and someone could use use your key without your permission.

**Comment by zk** [comment]
Oh wow, somehow I accidentally checked that in 🤦 .

I'll regen those keys, thanks for the heads up!

**Comment by zk** [comment]
Oh you know what, false alarm, those are dev friendly keys.

For example the mailgun account doesn't have payment info associated and the GH creds are for a dummy.

**Comment by sdushantha** [comment]
> Oh you know what, false alarm, those are dev friendly keys.


Oh thats good!
