### ISSUE TITLE
Minor typo in comment form docs

### ISSUE THREAD

**Issue by kraulain** [zk/clojuredocs#215]
# Background
While browsing through the docs for the `(comment )` form I found it a little hard to understand at first glance due to a typo in the word `(commment ...)` having 3 `m`
```
;; What is inside the (commment ...) is readable, so no error for this,
;; and no code will be generated by the compiler.
(comment
(defn foo [x]
  (inc x))
)

;; What is inside the (comment ...) is NOT readable, so this will give an error
(comment
a : b
)
```

# Requirement
Fix the typo to make the docs a little clearer

# Useful resources

- https://clojuredocs.org/clojure.core/comment

**Comment by zk** [comment]
Fixed!
