### ISSUE TITLE
Need to update Kira logo

### ISSUE THREAD

**Issue by syungb** [zk/clojuredocs#232]
I am from Kira Systems, and the company was rebranded in 2020, and has a new logo to update in [here](https://github.com/zk/clojuredocs/blob/master/resources/public/img/kira-logo.png). And here's a new logo:

![Kira-logo](https://user-images.githubusercontent.com/1319016/135486622-b84abb86-5602-440d-88d2-8f70cd936348.png)

I don't seem to have a permission to create a new branch to create a PR, so if someone who could update this logo, I would greatly appreciate it. Thanks!

**Comment by dotemacs** [comment]
Hey @syungb 

If you create a fork of the project, under your own GitHub account, you'll be able to add the change and create a pull request.
