### ISSUE TITLE
Update ClojureDocs to v1.11

### ISSUE THREAD

**Issue by Crowbrammer** [zk/clojuredocs#238]
I.e. add the `clojure.math` namespace and the following functions to `clojure.core`

\- [abs](https://clojure.github.io/clojure/clojure.core-api.html#clojure.core/abs) 
\- [NaN?](https://clojure.github.io/clojure/clojure.core-api.html#clojure.core/NaN?)
\- [infinite?](https://clojure.github.io/clojure/clojure.core-api.html#clojure.core/infinite?) 
\- [parse-double](https://clojure.github.io/clojure/clojure.core-api.html#clojure.core/parse-double) 
\- [parse-long](https://clojure.github.io/clojure/clojure.core-api.html#clojure.core/parse-long) 
\- [parse-boolean](https://clojure.github.io/clojure/clojure.core-api.html#clojure.core/parse-boolean) 
\- [parse-uuid](https://clojure.github.io/clojure/clojure.core-api.html#clojure.core/parse-uuid) 
\- [random-uuid](https://clojure.github.io/clojure/clojure.core-api.html#clojure.core/random-uuid) 
\- [update-keys](https://clojure.github.io/clojure/clojure.core-api.html#clojure.core/update-keys) 
\- [update-vals](https://clojure.github.io/clojure/clojure.core-api.html#clojure.core/update-vals) 
\- [iteration](https://clojure.github.io/clojure/clojure.core-api.html#clojure.core/iteration).

**Comment by Tiv0w** [comment]
It seems like the needed change is to bump the `org.clojure/clojure` to version 1.11.x.
This should suffice to make the functions appear and contributors could then add examples and docs.

**Comment by NoahTheDuke** [comment]
@zk I know you're busy with life and work and stuff, but this would be a really nice update for the community.

**Comment by NoahTheDuke** [comment]
Hey @zk, any news?

**Comment by zk** [comment]
Nope, will close this ticket when it's done.

**Comment by eval** [comment]
Would it help if I submit a PR for this issue @zk? Or is it already being worked on?

**Comment by ieugen** [comment]
hello @zk , the browser still opens clojure 1.10 version for me.

![Captură de ecran_2023-08-18_12-40-48](https://github.com/zk/clojuredocs/assets/1050920/56e13dda-3a34-43ed-8479-525388dfcc83)
