### ISSUE TITLE
4clojure link is dead

### ISSUE THREAD

**Issue by vstenvik** [zk/clojuredocs#241]
![bilde](https://user-images.githubusercontent.com/42935080/171565181-9a9a50da-7dc1-40a6-9cd3-6cdcad50719b.png)

Looks like 4clojure has been shut down. An alternative service is available at https://4clojure.oxal.org/

**Comment by Tiv0w** [comment]
Already fixed in the source, but the fix hasn't been deployed yet :slightly_smiling_face:

**Comment by CarnunMP** [comment]
Came here to submit the same issue, fwiw. :)
