### ISSUE TITLE
Slow responses from the live site today

### ISSUE THREAD

**Issue by harold** [zk/clojuredocs#245]
Hi, hope you're well. The Clojuredocs website is really great, I use it every day in my work and I'm grateful for your efforts.

I am getting slow/throttled/incomplete responses from the site today, including the homepage: https://clojuredocs.org/

Is there anything I can do to help?

Regardless, thanks again and stay rad (:

**Comment by zk** [comment]
Hey Harold, thanks for the report. I'm seeing this on the homepage as well
(it looks like a few of the images on the homepage are taking 30+ seconds
to load), but I'm not seeing it on any other pages. Do you remember which
specific pages other than the homepage you were seeing this on?

**Comment by ivarref** [comment]
Hi and thanks for a great site!

Maybe related: some cursive users are having trouble downloading the export file:

```bash
$ curl https://clojuredocs.org/clojuredocs-export.json > export.json
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  2 3348k    2 73534    0     0   1120      0  0:51:01  0:01:05  0:49:56     0
curl: (92) HTTP/2 stream 0 was not closed cleanly: INTERNAL_ERROR (err 2)
```

**Comment by hxegon** [comment]
Also seeing this, also looks like the JS request. Happens on all pages for me.

**Comment by ertugrulcetin** [comment]
Having the same problem

**Comment by harold** [comment]
Hey! It looks to be back now, which is great. Thanks for all you do.

Interestingly, this wrinkle got me to dig deeper into how docs can be explored inside Cider and I learned many things and am smarter for it. Hope everyone is doing well here in the late fall of 2022. :slightly_smiling_face: :fallen_leaf:

**Comment by zk** [comment]
Thanks @harold! So turns out the disk was out of space (whoops), cleaned that up and adding an alarm. Please reopen if you're still getting timeouts.

**Comment by harold** [comment]
👍🏻
