### ISSUE TITLE
Search API does not return Vars from Cloure 1.4 and later

### ISSUE THREAD

**Issue by jafingerhut** [zk/clojuredocs#86]
Not sure if the API access is planned to be updated or not, but at least in my brief testing using the old cd-client library, new symbols like clojure.core/unsigned-bit-shift-right never show up in search results.

**Comment by zk** [comment]
Punting on an API for the foreseeable future

**Comment by jafingerhut** [comment]
For anyone that might happen across this old issue, I have found the publishing and regular updating of the complete data at https://clojuredocs.org/clojuredocs-export.json to be a reasonable alternative for those who want to publish the docs in a different form.
